import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/site";

// Force dynamic so the `Sitemap:` URL reflects the actual runtime
// NEXT_PUBLIC_SITE_URL of the deployed env, not the build-time
// default. Without this, Next.js prerenders robots.txt once using
// whatever env was present during `next build` (typically the
// localhost fallback), and a deploy to staging/prod would ship a
// stale sitemap URL — exactly the CSP/HSTS class bug caught in #124.
export const dynamic = "force-dynamic";

// /robots.txt (#135). Minimal, explicit directives:
//   - Allow the public surface: homepage, articles, profiles.
//   - Disallow the authenticated-only editor + settings pages —
//     they 302 to /login for anon visitors anyway, but listing them
//     in robots saves crawlers a wasted round-trip.
//   - Disallow /api/ — the JSON surface isn't indexable content.
//   - Point to /sitemap.xml so crawlers pick up the dynamic
//     sitemap (generated by app/sitemap.ts).
//
// `NEXT_PUBLIC_SITE_URL` is the canonical origin shared with the OG
// metadata route (#113). Kept consistent so the sitemap URL in
// robots matches what crawlers fetch for each article's og:url.

export default function robots(): MetadataRoute.Robots {
  const origin = siteUrl();
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/editor", "/editor/", "/settings", "/api/"],
      },
    ],
    sitemap: `${origin}/sitemap.xml`,
  };
}
