#!/usr/bin/env bash
# dev-bootstrap — generate a local .env with random secrets on first run.
#
# Idempotent: if .env already exists, preserves all values and only
# fills in anything that is still missing.
#
# Called by:
#   - operator manually before `docker compose up`
#   - CI before spinning up compose for smoke tests
#
# No arguments. Writes .env in the repo root (gitignored).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

gen_hex() {
  # 64 hex chars = 256 bits, adequate for HS256.
  openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 256
}

get_or_default() {
  local key="$1" default_value="$2"
  if [[ -f "$ENV_FILE" ]]; then
    local existing
    existing=$(grep -E "^${key}=" "$ENV_FILE" | tail -1 | cut -d= -f2- || true)
    if [[ -n "${existing:-}" ]]; then
      printf '%s' "$existing"
      return
    fi
  fi
  printf '%s' "$default_value"
}

POSTGRES_USER=$(get_or_default POSTGRES_USER "conduit")
POSTGRES_DB=$(get_or_default POSTGRES_DB "conduit")
POSTGRES_PASSWORD=$(get_or_default POSTGRES_PASSWORD "$(gen_hex)")
JWT_SECRET=$(get_or_default JWT_SECRET "$(gen_hex)")

NODE_ENV=$(get_or_default NODE_ENV "development")
LOG_LEVEL=$(get_or_default LOG_LEVEL "info")

WEB_HOST_PORT=$(get_or_default WEB_HOST_PORT "3000")
WEB_PORT=$(get_or_default WEB_PORT "3000")
API_HOST_PORT=$(get_or_default API_HOST_PORT "3001")
API_PORT=$(get_or_default API_PORT "3001")
POSTGRES_HOST_PORT=$(get_or_default POSTGRES_HOST_PORT "5432")

JWT_TTL_SECONDS=$(get_or_default JWT_TTL_SECONDS "604800")
COOKIE_DOMAIN=$(get_or_default COOKIE_DOMAIN "localhost")
COOKIE_SECURE=$(get_or_default COOKIE_SECURE "false")

WEB_URL=$(get_or_default WEB_URL "http://localhost:${WEB_HOST_PORT}")
API_URL_INTERNAL=$(get_or_default API_URL_INTERNAL "http://api:${API_PORT}")
NEXT_PUBLIC_API_URL=$(get_or_default NEXT_PUBLIC_API_URL "http://localhost:${API_HOST_PORT}")

cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev-bootstrap.sh — safe to re-run.
# DO NOT commit this file. Add only new keys here; secrets are
# preserved across re-runs when the key already has a value.

NODE_ENV=${NODE_ENV}
LOG_LEVEL=${LOG_LEVEL}

# ── Postgres ────────────────────────────────────────────────────
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}

# ── API ─────────────────────────────────────────────────────────
API_PORT=${API_PORT}
API_HOST_PORT=${API_HOST_PORT}
API_URL_INTERNAL=${API_URL_INTERNAL}

# ── Web ─────────────────────────────────────────────────────────
WEB_PORT=${WEB_PORT}
WEB_HOST_PORT=${WEB_HOST_PORT}
WEB_URL=${WEB_URL}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

# ── Auth ────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_TTL_SECONDS=${JWT_TTL_SECONDS}
COOKIE_DOMAIN=${COOKIE_DOMAIN}
COOKIE_SECURE=${COOKIE_SECURE}
EOF

echo "[dev-bootstrap] wrote ${ENV_FILE}"
